import Head from 'next/head'
import { Inter } from 'next/font/google'
import style from '@/styles/Home.module.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/navbar/Footer'
import Contact from '@/components/contact/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Foodit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={style["main"]}>
        <div className={style["introduction-container"]}>
          <h1>Welcome to "foodit"!</h1>
          <p>Delicious Food Delivered to Your Doorstep</p>

          <div className={`${style["features"]} ${style["d-flex"]} ${style["flex-column"]}`}>
            <div className={style["feature"]}>
              <span role="img" aria-label="Fast Delivery">🍔</span>
              <h2>Quick, Easy, and Convenient</h2>
              <p>Order your favorite food from local restaurants, hassle-free.</p>
            </div>
            <div className={style["feature"]}>
              <span role="img" aria-label="Wide Range of Options">🌮</span>
              <h2>Wide Range of Options</h2>
              <p>From pizzas to sushi, we've got something for everyone. Explore diverse menus and find your cravings.</p>
            </div>
            <div className={style["feature"]}>
              <span role="img" aria-label="Fast Delivery">⏰</span>
              <h2>Fast Delivery</h2>
              <p>Hungry? We've got you covered with lightning-fast delivery straight to your doorstep.</p>
            </div>
          </div>
        </div>
      </main>
      <Contact />
      <Footer />
    </>
  )
}
